In [1]:
import pandas as pd

In [24]:
#import sys
#sys.path

p_cctv = pd.read_csv("./data/pusan_cctv.csv",encoding = 'euc-kr')

In [25]:
p_cctv.head()

,관리기관명,소재지도로명주소,소재지지번주소,설치목적구분,카메라대수,카메라화소수,촬영방면정보,보관일수,설치년월,관리기관전화번호,위도,경도,데이터기준일자
0,부산광역시,부산광역시 해운대구 송정중앙로 14,부산광역시 해운대구 송정동 349,다목적,1,200,100m이내,30,2010-01,051-888-2991,35.182530,129.203479,2018-04-30
1,부산광역시,부산광역시 금정구 부곡2동 233-1,부산광역시 금정구 서동 282-57,다목적,1,200,100m이내,30,2011-01,051-888-2991,35.216551,129.102759,2018-04-30
2,부산광역시,부산광역시 금정구 서3동 132-29,부산광역시 금정구 서3동 132-29,다목적,1,200,100m이내,30,2011-01,051-888-2991,35.224488,129.095603,2018-04-30
3,부산광역시,부산광역시 금정구 장전1동 170-2,부산광역시 금정구 장전1동 170-2,다목적,1,200,100m이내,30,2011-01,051-888-2991,35.229427,129.120716,2018-04-30
4,부산광역시,부산광역시 금정구 서2동 302-1042,부산광역시 금정구 서동 302-1042,다목적,1,200,100m이내,30,2011-01,051-888-2991,35.230635,129.087668,2018-04-30

In [26]:
p_cctv = p_cctv.iloc[:,2:-1]

In [32]:
p_cctv.rename(columns = {'소재지지번주소':'구군'}, inplace = True)

In [34]:
p_cctv.head()

,구군,설치목적구분,카메라대수,카메라화소수,촬영방면정보,보관일수,설치년월,관리기관전화번호,위도,경도
0,부산광역시 해운대구 송정동 349,다목적,1,200,100m이내,30,2010-01,051-888-2991,35.182530,129.203479
1,부산광역시 금정구 서동 282-57,다목적,1,200,100m이내,30,2011-01,051-888-2991,35.216551,129.102759
2,부산광역시 금정구 서3동 132-29,다목적,1,200,100m이내,30,2011-01,051-888-2991,35.224488,129.095603
3,부산광역시 금정구 장전1동 170-2,다목적,1,200,100m이내,30,2011-01,051-888-2991,35.229427,129.120716
4,부산광역시 금정구 서동 302-1042,다목적,1,200,100m이내,30,2011-01,051-888-2991,35.230635,129.087668

In [37]:
p_cctv['구군'] = p_cctv['구군'].apply(lambda a: a.split(' ')[1])

In [39]:
p_cctv.head()

,구군,설치목적구분,카메라대수,카메라화소수,촬영방면정보,보관일수,설치년월,관리기관전화번호,위도,경도
0,해운대구,다목적,1,200,100m이내,30,2010-01,051-888-2991,35.182530,129.203479
1,금정구,다목적,1,200,100m이내,30,2011-01,051-888-2991,35.216551,129.102759
2,금정구,다목적,1,200,100m이내,30,2011-01,051-888-2991,35.224488,129.095603
3,금정구,다목적,1,200,100m이내,30,2011-01,051-888-2991,35.229427,129.120716
4,금정구,다목적,1,200,100m이내,30,2011-01,051-888-2991,35.230635,129.087668

In [61]:
p_cctv = p_cctv.loc[:,['구군','카메라대수']]
p_cctv.head()

In [62]:
p_cctv = p_cctv.groupby('구군').sum()
p_cctv.head()

     카메라대수
구군
강서구    274
금정구    313
기장군    273
남구     271
동구     254

In [9]:
p_pop = pd.read_csv("./data/pusan_pop.csv",encoding = 'euc-kr')
p_pop.head()

,구군,동수 (개소),세대수 (세대),인구수 (명),남자인구수 (명),여자인구수 (명),시전체 인구에 대한 구성비 (%),면적 (㎢),인구밀도 (명/㎢)
0,중구,9,23089,45408,22524,22884,1.3,2.83,"16,045"
1,서구,13,52500,112445,55220,57225,3.2,13.98,"8,043"
2,동구,12,43326,89842,44265,45577,2.6,9.74,"9,224"
3,영도구,11,55534,123735,61454,62281,3.5,14.19,"8,720"
4,부산진구,20,166084,370440,180298,190142,10.6,29.67,"12,485"

In [76]:
pusan_total = pd.merge(p_cctv, p_pop, on  = '구군')
pusan_total.head()
# inner 똑같음(교집합) left right(각각이 중심이 되서), outer 합집합

,구군,카메라대수,동수 (개소),세대수 (세대),인구수 (명),남자인구수 (명),여자인구수 (명),시전체 인구에 대한 구성비 (%),면적 (㎢),인구밀도 (명/㎢)
0,강서구,274,8,48718,124629,66222,58407,3.6,181.49,687
1,금정구,313,17,105690,248606,121769,126837,7.1,65.27,"3,809"
2,기장군,273,5,66765,165318,82211,83107,4.7,218.30,757
3,남구,271,17,115729,283384,139248,144136,8.1,26.81,"10,570"
4,동구,254,12,43326,89842,44265,45577,2.6,9.74,"9,224"

In [81]:
import numpy as np
pusan_total['카메라대수']

0     274
1     313
2     273
3     271
4     254
5     282
6     305
7     292
8     294
9     291
10    247
11    260
12    271
13    245
14    229
15    297
Name: 카메라대수, dtype: int64

In [83]:
np.corrcoef(pusan_total['카메라대수'],pusan_total['인구수 (명)'])

array([[1.        , 0.82384443],
       [0.82384443, 1.        ]])